[package]
name = "framebrush"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["wrap"]
wrap = []

[dependencies]

[dev-dependencies]
softbuffer = "0.3.0"
winit = "0.28.6"
minifb = "0.27.0"
